name: C Hello World Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: actions/setup-gcc@v1
        with:
          gcc-version: 'latest'

      - name: Compile Hello World
        run: gcc -o hello hello.c

      - name: Run Hello World
        run: ./hello
