name: C Hello World Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Compile Hello World
        run: gcc -o hello hello.c

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: hello-executable
          path: hello
