name: C Hello World Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Compile Hello World for Windows
        run: x86_64-w64-mingw32-gcc -o hello.exe hello.c

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: hello-windows-executable
          path: hello.exe
